<?xml version="1.0" encoding="UTF-8"?><testrun name="FactoryNumberValidatorShould" project="VehicleAssemblyLine" tests="6" started="6" failures="1" errors="0" ignored="0">
  <testsuite name="org.talentboost.assembly.validators.tests.FactoryNumberValidatorShould" time="0.003">
    <testcase name="validate_unvalidNumber_returnFalse" classname="org.talentboost.assembly.validators.tests.FactoryNumberValidatorShould" time="0.0"/>
    <testcase name="validate_validNumberCornerCase_returnTrue" classname="org.talentboost.assembly.validators.tests.FactoryNumberValidatorShould" time="0.0"/>
    <testcase name="validate_unvalidNumberCornerCase_returnFalse" classname="org.talentboost.assembly.validators.tests.FactoryNumberValidatorShould" time="0.0"/>
    <testcase name="validate_validNumber_returnTrue" classname="org.talentboost.assembly.validators.tests.FactoryNumberValidatorShould" time="0.0"/>
    <testcase name="validate_unvalidNumberNegative_returnFalse" classname="org.talentboost.assembly.validators.tests.FactoryNumberValidatorShould" time="0.0"/>
    <testcase name="validate_unvalidFormat_throwNumberFormatException" classname="org.talentboost.assembly.validators.tests.FactoryNumberValidatorShould" time="0.003">
      <failure>java.lang.AssertionError: Expected exception: java.lang.NumberFormatException&#13;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
</testrun>
